<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner" style="background-color: #1da1f2;">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div style="font-weight: bold; color: white;">
				<div class="communicationItem" style="margin-bottom: 28px;">
					<i class="fas fa-search fa-2x mr-3"></i>
					Siga o que lhe interessa.
				</div>
				<div class="communicationItem" style="margin-bottom: 28px;">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Saiba sobre o que as pessoas estão falando.
				</div>
				<div class="communicationItem" style="margin-bottom: 28px;">
					<i class="far fa-comment fa-2x mr-3"></i>
					Participe da conversa.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form>
			<div class="row">
				<div class="col">
					<input type="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="img/twitter_logo.png" />
				<h1 class="title" style="color: #1da1f2; margin-top: 16px;">Veja o que está acontecendo no mundo agora</h1>

				<h2 class="mt-5 subtitle" style="font-size: 26px; font-weight: bold; margin-bottom: 12px;">Participe hoje do Twitter.</h2>
				<a href="inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>